### ISSUE TITLE
DM to new followers

### ISSUE THREAD

**Issue by iransales** [instagrambot/instabot#492]
Please can you implement send DM to new followers. **PLEASE**

**Comment by sudoguy** [comment]
I did write some script in examples. Welcome
https://github.com/instagrambot/instabot/blob/master/examples/welcome_message.py

**Comment by choskii** [comment]
I saw your script for direct message to new followers. I'm a beginner, and have Instabot already configured running.
Where should I add or run your script for automatic dm?
Thank you so much!

**Comment by constantinosbou** [comment]
Yes, please more info!

**Comment by RobertoBrandini** [comment]
i'm receiving this error

Traceback (most recent call last):
  File "welcome_message.py", line 15, in <module>
    from instabot import Bot, utils
ImportError: cannot import name 'utils'
D:\Fabrica_Python\instagrambot\examples>

**Comment by RobertoBrandini** [comment]
solved using  pip install huepy==0.9.8.1

**Comment by LucSpan** [comment]
I get the following error when the script intends to send a DM to a new follower: 

`2018-05-08 09:17:16,838 - ERROR - Request returns 400 error!`
`2018-05-08 09:17:16,839 - INFO - Instagram's error message: feedback_required`
`2018-05-08 09:17:16,839 - INFO - Message to ['xxx'] wasn't sent`

What is this `feedback_required`?

------

I found [this article](https://www.gramto.com/article/fix-instagram-feedback-required-error/) explaining it. Has nothing to do with the code, it seems.

**Comment by eyazilikaya** [comment]
Thanks @sudoguy for your script. I wonder if we can print username in the message ? for example, if I'm sending a message to sudoguy, message should be something like this "thank you for follow @username " is that possible somehow?

**Comment by basnijholt** [comment]
@eyazilikaya 
just make the message:
```python
'Thank you for following me @{}'.format(bot.get_user_info(follower)['username'])
```

so change the last lines into:
```python
for follower in tqdm(new_followers):
    MESSAGE = 'Thank you for following me @{}'.format(bot.get_user_info(follower)['username'])
    if bot.send_message(MESSAGE, follower):
        notified_users.append(follower)
```

**Comment by iransales** [comment]
How do I send more than one message? For example:
1 *: Hi @marcel
2 *: We have the best prices
3 *: contact us by email

**Comment by iransales** [comment]
Can someone answer my question above?

**Comment by iransales** [comment]
@basnijholt ?

**Comment by basnijholt** [comment]
@iransales could you write what you tried yourself in order to do this?

**Comment by StudioBloomDMVR** [comment]
also receiving 
```Traceback (most recent call last):
  File "/Users/knux/Desktop/instabot-master/examples/welcome_message.py", line 15, in <module>
    from instabot import Bot, utils
ImportError: cannot import name 'utils' 
```

attempted ```install huepy==0.9.8.1``` as @RobertoBrandini states but that returns
```Collecting huepy
  Could not fetch URL https://pypi.python.org/simple/huepy/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement huepy (from versions: )
No matching distribution found for huepy```

**Comment by williamwil777** [comment]
is there anyway I can modify the script to DM users that I follow ? @sudoguy

**Comment by akechidi02** [comment]
need some help to dm my followers any one ????

**Comment by MrsJeffIngle2019** [comment]
hi
